### ISSUE TITLE
Wrong require in readme

### ISSUE THREAD

**Issue by lukasoppermann** [ragingwind/pwa-manifest#2]
Hey,

I actually have to require `@pwa/manifest`.

`const pwaManifest = require('@pwa/manifest')`

**Comment by ragingwind** [comment]
Thanks for reporting. Updated it https://github.com/ragingwind/pwa-manifest/commit/5f25c3ee008aacb6a7eb2a64f48bc1b90a573c9c#diff-0730bb7c2e8f9ea2438b52e419dd86c9

**Comment by lukasoppermann** [comment]
Neat.
